version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_BACKEND_PUBLIC_URL=${NEXT_PUBLIC_BACKEND_PUBLIC_URL}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
      - NEXT_PUBLIC_BACKEND_PUBLIC_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./tmp:/app/tmp

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./tmp:/app/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - animation-service

  animation-service:
    build: ./python
    volumes:
      - ./tmp:/app/tmp
    command: python flask_wrapper.py